language: python
python:
  - "3.9"
install:
    - pip install -r requirements.txt
    - pip install pyyaml
    - pip install coverage
    - pip install coveralls

branches:
  only:
    - master
after_success:
  coveralls
